# -*- coding: utf-8 -*-
"""Internship.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_Q8PgO7UAUeELJQ8PlqPYKYFW9Tov-s4

VIRTUAL INTERNSHIP



Internship Available on-

1. Machine Learning

2. IOT

3. Data Science

4. Cloud Computing

5. Internet Security

6. Hacking

7. Web Development

8. Cryptography

Interns will get Internship Certificate, Prize and Perks.

Rs. 3000 Stipend will also be given to Interns after completion of Internships !

2-6 Weeks Internship are going on as per your preferences.

Send your Resume, Queries or Question on vatshayan007@gmail.com for Internship.
""

Mail me your Resume or any Queries at **vatshayan007@gmail.com** Now!
"""

